
version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\rai-project\rai
shallow_clone: true

environment:
  GOPATH: C:\gopath
  matrix:
    - environment:
      GOVERSION: 1.10.3

platform:
- x64

init:
- git config --global core.autocrlf input

install:
# Install the specific Go version.
- rmdir c:\go /s /q
- appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
- msiexec /i go%GOVERSION%.windows-amd64.msi /q
- set Path=c:\go\bin;c:\gopath\bin;%Path%
- go version
- go env
- go get -u github.com/golang/dep/cmd/dep


test_script:
- C:\gopath\bin\dep ensure -v
- go build

build: false
deploy: false
